### ISSUE TITLE
Request for Code Related to Variants in Paper

### ISSUE THREAD

**Issue by 2004learner** [HornHehhf/RR#2]
Hello,

I have cloned the repository, but I am having some difficulty understanding the content related to the variant mentioned in the paper. Could you please provide the code for the experimental part of the variants discussed? It would be greatly helpful for my understanding.

Thank you in advance for your assistance!

Best regards

**Comment by HornHehhf** [comment]
Thank you for reaching out! Unfortunately, it's a bit challenging for me to find, reorganize and test the code for this analysis, as some time has passed. However, I hope Section 5.3 and Appendix A.4 provide the information you need.
